//
// Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

[[introduction]]
== Introduction
In cloud-native technology stacks, distributed and polyglot architectures are the norm.
Distributed architectures introduce a variety of operational challenges including how to solve availability and performance issues quickly.
These challenges have led to the rise of observability.

Telemetry data is needed to power observability products.
Traditionally, telemetry data has been provided by either open-source projects or commercial vendors.
With a lack of standardization, the net result is the lack of data portability and the burden on the user to maintain the instrumentation.

The https://opentelemetry.io[OpenTelemetry] project solves these problems by providing a single, vendor-agnostic solution.

== Architecture
https://opentelemetry.io[OpenTelemetry] is a set of APIs, SDKs, tooling and integrations that are designed for the creation and management of telemetry data such as traces, metrics, and logs.

This specification defines the behaviors that allow MicroProfile applications to easily participate in an environment where distributed tracing is enabled via https://opentelemetry.io[OpenTelemetry].

The OpenTelemetry specification describes the cross-language requirements and expectations for all OpenTelemetry implementations.
This specification is based on the https://github.com/open-telemetry/opentelemetry-java/tree/v{otel-java-version}[Java implementation v{otel-java-version}] of OpenTelemetry. An implementation of this MicroProfile Telemetry MAY consume a later patch release of the Java implementation as long as the required TCKs pass successfully.

Refer to the OpenTelemetry specification repo to understand some essential terms.

* https://opentelemetry.io/docs/specs/otel/overview/[OpenTelemetry Overview]
* https://opentelemetry.io/docs/specs/otel/trace/api/[Tracing API]
* https://opentelemetry.io/docs/specs/otel/baggage/api/[Baggage API]
* https://opentelemetry.io/docs/specs/otel/context/[Context API]
* https://opentelemetry.io/docs/specs/otel/resource/sdk/[Resource SDK]

[IMPORTANT]
====
The Logging integrations of https://opentelemetry.io[OpenTelemetry] are out of scope of this specification.
Implementations are free to provide support for Logging if desired.
====