//
// Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

[[metrics]]
== Metrics

Metrics are captured measurements of applications' and runtime's behavior.
An application may provide metrics of its own in addition to the metrics provided by the runtime.

Implementations are required to capture certain <<required_metrics,required metrics>> such as JVM performance counters and HTTP request processing times. Custom metrics can be defined by utilizing <<metrics_api,Metrics API>> as following example demostrates:

[source,java]
----
class WithCounter {
    @Inject
    Meter meter;

    private LongCounter counter;

    @PostConstruct
    public void init() {
        counter = meter
                    .counterBuilder("new_subscriptions")
                    .setDescription("Number of new subscriptions")
                    .setUnit("1")
                    .build();
    }

    void subscribe(String plan) {
        counter.add(1,
            Attributes.of(AttributeKey.stringKey("plan"), plan));
    }
}
----
In this example `Meter` is used to define an instrument, in this case a Counter and application code then can record measurement values along with additional attributes.
Measurement aggregations are computed separately for each unique combination of attributes.

=== Routing Metrics
OpenTelemetry can be enabled selectively for each application, or globally for the runtime and all applications as described in <<sec:enabling-opentelemetry-support>>. Metrics may be registered by applications or on behalf of a component in the runtime. For example, a counter metric that is registered by an application to track the number of cars driving over a bridge is an application metric, whereas a gauge tracking the amount of memory used by the JVM is a runtime metric.

For metrics that are registered by an application:

- if the OpenTelemetry SDK instance is shared by the runtime and applications then application-registered metrics should be routed to this instance
- if an OpenTelemetry SDK instance is enabled for the application that is registering a metric then that metric should be routed to this instance
- if no OpenTelemetry SDK instance is enabled for the application that is registering a metric then that metric should be discarded (typically by sending the registration request to a noop OpenTelemetry SDK instance)

For metrics that originate from the runtime:

- if the OpenTelemetry SDK instance is shared by the runtime and applications then runtime-registered metrics should be routed to this instance
- if no OpenTelemetry SDK instance is shared by the runtime and applications then runtime-registered metrics from the runtime should be discarded (typically by sending the registration request to a noop OpenTelemetry SDK instance)

[#metrics_api]
=== Access to the OpenTelemetry Metrics API
An implementation of MicroProfile Telemetry Metrics MUST provide the following CDI beans for supporting contextual instance injection:

* `io.opentelemetry.api.metrics.Meter`

[#required_metrics]
=== Required Metrics

The following metrics MUST be provided by runtimes. These are as defined in the OpenTelemetry Semantic Conventions v{otel-semconv-version} 

All attributes that are listed as required and stable in the OpenTelemetry Semantic Conventions MUST be included.

All attributes that are listed as conditionally required and stable in the OpenTelemetry Semantic Conventions MUST be included when the per-attribute condition described in the OpenTelemetry Semantic Conventions is satisfied.

All attributes that are listed as recommended and stable in the OpenTelemetry Semantic Conventions SHOULD be included if they are readily available and can be efficiently populated.

All attributes that are listed as Opt-In and stable in the OpenTelemetry Semantic Conventions MUST NOT be included unless the implementation provides a means for users to configure which Opt-In attributes to enable. This requirement is based on OpenTelemetry Semantic Conventions documentation indicating that Opt-In attributes MUST NOT be included unless the user has a way to choose if they are enabled/disabled.

Attribute values and usage guidelines as defined in the semantic conventions document MUST be followed.

// Table with metric name and attributes
[options="header"]
|===
|Metric Name |Type |Attributes

3+h| HTTP Server

|`http.server.request.duration`
| Histogram
a|required attributes

* `http.request.method`
* `url.scheme`

conditionally required

* `error.type`
* `http.response.status_code`
* `http.route`
* `network.protocol.name`

recommended

* `network.protocol.version`

Opt-In

* `server.address`
* `server.port`

3+h| JVM Memory

|`jvm.memory.used`
|UpDownCounter
a|recommended

* `jvm.memory.pool.name`
* `jvm.memory.type`

|`jvm.memory.committed`
|UpDownCounter
a|recommended

* `jvm.memory.pool.name`
* `jvm.memory.type`

|`jvm.memory.limit`
|UpDownCounter
a|recommended

* `jvm.memory.pool.name`
* `jvm.memory.type`

|`jvm.memory.used_after_last_gc`
|UpDownCounter
a|recommended

* `jvm.memory.pool.name`
* `jvm.memory.type`

3+h| JVM Garbage Collection

|`jvm.gc.duration`
|Histogram
a|recommended

* `jvm.gc.action`
* `jvm.gc.name`

3+h| JVM Threads

|`jvm.thread.count`
|UpDownCounter
a|recommended

* `jvm.thread.daemon`
* `jvm.thread.state`

3+h| JVM Classes

|`jvm.class.loaded`
|Counter
|

|`jvm.class.unloaded`
|Counter
|

|`jvm.class.count`
|UpDownCounter
|

3+h| JVM CPU

|`jvm.cpu.time`
|Counter
|

|`jvm.cpu.count`
|UpDownCounter
|

|`jvm.cpu.recent_utilization`
|Gauge
|

|===

=== Metrics Enablement
Metrics are activated whenever Microprofile Telemetry is enabled, as described in <<sec:enabling-opentelemetry-support>>.
