//
// Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

[[tracing]]
== Tracing

In the observability, Tracing is used to diagnose problems. Tracing instrumentation is used to generate traces.

=== Tracing Instrumentation
This specification supports the following three types of instrumentation:

* <<sec:automatic-instrumentation>>
* <<sec:manual-instrumentation>>
* <<sec:agent-instrumentation>>

[[sec:automatic-instrumentation]]
==== Automatic Instrumentation
Jakarta RESTful Web Services (server and client) and MicroProfile REST Clients are automatically enlisted to participate in distributed tracing without code modification as specified in the Tracing API.

These SHOULD follow the rules specified in the <<sec:semantic-conventions>> section.

[[sec:manual-instrumentation]]
==== Manual Instrumentation
Explicit manual instrumentation can be added into a MicroProfile application in the following ways:

===== @WithSpan
Annotating a method in any Jakarta CDI aware beans with the `io.opentelemetry.instrumentation.annotations.WithSpan` annotation.
This will create a new Span and establish any required relationships with the current Trace context.

Method parameters can be annotated with the `io.opentelemetry.instrumentation.annotations.SpanAttribute` annotation to indicate which method parameters SHOULD be part of the Trace.

Example:
[source,java]
----
@ApplicationScoped
class SpanBean {
    @WithSpan
    void span() {

    }

    @WithSpan("name")
    void spanName() {

    }

    @WithSpan(kind = SpanKind.SERVER)
    void spanKind() {

    }

    @WithSpan
    void spanArgs(@SpanAttribute(value = "arg") String arg) {

    }
}
----

===== Obtain a SpanBuilder
By obtaining a `SpanBuilder` from the current `Tracer` and calling `io.opentelemetry.api.trace.Tracer.spanBuilder(String)`.
In this case, it is the developer's responsibility to ensure that the `Span` is properly created, closed, and propagated.

Example:
[source,java]
----
@RequestScoped
@Path("/")
public class SpanResource {
    @Inject
    Tracer tracer;

    @GET
    @Path("/span/new")
    public Response spanNew() {
        Span span = tracer.spanBuilder("span.new")
                .setSpanKind(SpanKind.INTERNAL)
                .setParent(Context.current().with(this.span))
                .setAttribute("my.attribute", "value")
                .startSpan();

        span.end();

        return Response.ok().build();
    }
}
----
 
[NOTE]
====
Start and end a new `Span` will add a child `Span` to the current one enlisted by the automatic instrumentation of Jakarta REST applications.
====

===== Obtain the current Span
By obtaining the current `Span` to add attributes.
The Span lifecycle is managed by the implementation.

Example:
[source,java]
----
@RequestScoped
@Path("/")
public class SpanResource {
    @GET
    @Path("/span/current")
    public Response spanCurrent() {
        Span span = Span.current();
        span.setAttribute("my.attribute", "value");
        return Response.ok().build();
    }
}
----

Or with CDI:
[source,java]
----
@RequestScoped
@Path("/")
public class SpanResource {
    @Inject
    Span span;

    @GET
    @Path("/span/current")
    public Response spanCurrent() {
        span.setAttribute("my.attribute", "value");
        return Response.ok().build();
    }
}
----

[[sec:agent-instrumentation]]
==== Agent Instrumentation
Implementations are free to support the OpenTelemetry Agent Instrumentation.
This provides the ability to gather telemetry data without code modifications by attaching a Java Agent JAR to the running JVM.

If an implementation of MicroProfile Telemetry Tracing provides such support, it MUST conform to the instructions detailed in the https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/v{otel-java-version}[OpenTelemetry Java Instrumentation] project, including:

* https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/[Agent Configuration]
* https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#suppressing-specific-auto-instrumentation[Suppressing Instrumentation]

Both Agent and MicroProfile Telemetry Tracing Instrumentation (if any), MUST coexist with each other.

=== Access to the OpenTelemetry Tracing API
An implementation of MicroProfile Telemetry Tracing MUST provide the following CDI beans for supporting contextual instance injection:

* `io.opentelemetry.api.trace.Tracer`
* `io.opentelemetry.api.trace.Span`
* `io.opentelemetry.api.baggage.Baggage`

Calling the OpenTelemetry API directly MUST work in the same way and yield the same results:

* `io.opentelemetry.api.trace.Span.current()`
* `io.opentelemetry.api.baggage.Baggage.current()`

[[sec:semantic-conventions]]
=== Trace Semantic Conventions
The https://github.com/open-telemetry/opentelemetry-java/tree/v{otel-java-version}/semconv/src/main/java/io/opentelemetry/semconv[Trace Semantic Conventions] for Spans and Attributes MUST be followed by any compatible implementation.

All attributes marked as `required` MUST be present in the context of the Span where they are defined.
Any other attribute is optional.
Implementations can also add their own attributes.

==== MicroProfile Attributes
Other MicroProfile specifications can add their own attributes under their own attribute name following the convention `mp.[specification short name].[attribute name]`.

Implementation libraries can set the library name using the following property:

`mp.telemetry.tracing.name`

=== Tracing Enablement
Tracing is activated whenever Microprofile Telemetry is enabled, as described in <<sec:enabling-opentelemetry-support>>.

=== MicroProfile OpenTracing
MicroProfile Telemetry Tracing supersedes MicroProfile OpenTracing.
Even if the end goal is the same, there are some considerable differences:

* Different API (between OpenTracing and OpenTelemetry)
* No `@Traced` annotation
* No specific MicroProfile configuration
* No customization of Span name through MicroProfile API
* Differences in attribute names and mandatory ones

For these reasons, the MicroProfile Telemetry Tracing specification does not provide any migration path between both projects.
While it is certainly possible to achieve a migration path at the code level and at the specification level (at the expense of not following the main OpenTelemetry specification), it is unlikely to be able to achieve the same compatibility at the data layer.
Regardless, implementations are still free to provide migration paths between MicroProfile OpenTracing and MicroProfile Telemetry Tracing. 

If a migration path is provided, the bridge layer provided by OpenTelemetry SHOULD be used.
This bridge layer implements OpenTracing APIs using OpenTelemetry API. The bridge layer takes OpenTelemetry Tracer and exposes as OpenTracing Tracer.
See the example below.

[source,java]
----
//From the global OpenTelemetry configuration
Tracer tracer1 = OpenTracingShim.createTracerShim();
//From a provided OpenTelemetry instance oTel
Tracer tracer2 = OpenTracingShim.createTracerShim(oTel);
----

Afterwards, you can then register the tracer as the OpenTracing Global Tracer:

[source,java]
----
GlobalTracer.registerIfAbsent(tracer);
----

[[sec:microprofile-telemetry-and-microprofile-opentracing]]
=== MicroProfile Telemetry and MicroProfile OpenTracing
If MicroProfile Telemetry and MicroProfile OpenTracing are both present in one application, it is recommended to only enable one of them, otherwise non-portable behaviour MAY occur.
