//
// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= MicroProfile Telemetry

image:https://badges.gitter.im/eclipse/microprofile-telemetry.svg[link="https://gitter.im/eclipse/microprofile-telemetry?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

This specification is to adopt https://opentelemetry.io/[OpenTelemetry] from CNCF to allow MicroProfile Applications benefit from OpenTelemetry and enable Jakarta RESTful Web Services automatically being traced if configured.

== Directly adopt the APIs from OpenTelemetry APIs
This specification directly expose the Tracing and Metrics APIs from OpenTelemetry and then provide CDI and Jakarta RESTful Web Services integration.
The https://github.com/open-telemetry/opentelemetry-java/tree/main/api/all/src/main/java/io/opentelemetry/api/metrics Metrics APIs from OpenTelemetry will be exposed.

The https://github.com/open-telemetry/opentelemetry-java/tree/main/api/all/src/main/java/io/opentelemetry/api/tracing Tracing APIs from OpenTelemetry will be exposed.

This specification does not plan to reinvent the wheels but rather exposes OpenTelemetry APIs due to the following reasons:

* OpenTelemetry is a specification under CNCF
* OpenTelemetry is widely adopted by different vendors and languages
* OpenTelemetry has Java API and annotations that are readily to be used
* OpenTelemetry is active and open for the collaboration with us
* OpenTelemetry is platform technology and we use the effort to make Java libraries to be used directly instead of reinventing our own APIs
* OpenTelemetry has broad vendor support.
Many observability vendors are contributing to the spec, providing a guarantee that traces can be used out of the box, with minimal integrations.
* OpenTelemetry is serious with backward incompatible changes and communicates openly

MicroProfile Telemetry pulls in a particular version of OpenTelemetry.
Whenever we upgrade, we evaluate the backward compatibility status ourselves as well.


== OpenTracing moves to OpenTelemetry
With the merge of OpenTracing and OpenCensus, OpenTelemetry holds the future.
OpenTelemetry consists of Tracing, Logging, Metrics and Baggage support.

== Structure of this Specification
Since OpenTelemetry has three main parts and an additional one:
Tracing, Metrics, Logging and Baggage for additional information, i.e. to link between them.
This specification potentially adopts all three main parts when they are stable in OpenTelemetry.
If this is the case, they will appear as submodules in this specification. 
For instance, you can find details related to `tracing` from the directory of `tracing`.
This top level project specifies a particular version of OpenTelemetry to pull in so that all submodules can work together.

[NOTE]
====
Currently implementations of this specification are required to support Tracing and Baggage only.
====
