//
// Copyright (c) 2022-2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= MicroProfile Telemetry Metrics TCK
Any MicroProfile Telemetry implementation must pass this test suite.
The TCK uses `TestNG` and `Arquillian`.

== Hardware Requirements
All systems should meet the following recommended hardware requirements:

    * CPU running at 2.0 GHz or higher
    * 4 GB of RAM or more
    * Network access to the Internet

== Software Requirements
You can run this TCK on platforms running the Solaris, Linux, Windows, and Mac OS with the following software installed:

    * Maven
    * JDK11+

== Dependencies
To enable the tests in your project you need to add the following dependency to your build:

[source, xml]
----

<dependency>
    <groupId>org.eclipse.microprofile.telemetry</groupId>
    <artifactId>microprofile-telemetry-metrics-tck</artifactId>
    <version>2.0</version>
    <scope>test</scope>
</dependency>

----

== Running the tests

The JVM metrics tests require runtime configuration to enable metric reading at a runtime level. The metrics must be sent to stdout in the tests. Ensure logs written to stdout are captured in a file and set the system property `log.file.path` to the file containing the log output when running the logs TCK. Configure the runtime with the following as system properties / environment variables:

 * otel.sdk.disabled=false/OTEL_SDK_DISABLED=FALSE
 * otel.metrics.exporter=logging/OTEL_METRICS_EXPORTER=LOGGING
 * otel.traces.exporter=none/OTEL_TRACES_EXPORTER=none
 * otel.logs.exporter=none/OTEL_LOGS_EXPORTER=none
 * otel.metric.export.interval=3000/OTEL_METRIC_EXPORT_INTERVAL=3000

To run the JVM metrics tests, include the following content in the `tck-suite.xml` in your project:

[source, xml]
----
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="microprofile-telemetry-metrics-TCK" verbose="2" configfailurepolicy="continue" >
    <test name="telemetry-metrics-tests" verbose="10">
        <packages>
            <package name="org.eclipse.microprofile.telemetry.metrics.tck.jvm.*" />
        </packages>
    </test>
</suite>
----

The remaining metrics tests must use an OpenTelemetry SDK instance that is configured by the configuration properties set in the application. Ensure that `otel.sdk.disabled` and `otel.metrics.exporter` are NOT set by the runtime. To run the application metrics tests, include the following content in the `tck-suite.xml` in your project:

[source, xml]
----
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="microprofile-telemetry-metrics-TCK" verbose="2" configfailurepolicy="continue" >
    <test name="telemetry-metrics-tests" verbose="10">
        <packages>
            <package name="org.eclipse.microprofile.telemetry.metrics.tck.application.*" />
        </packages>
    </test>
</suite>
----

== Configuration in Apache Maven pom.xml
If you use Apache Maven then the tests are run via the `maven-surefire-plugin`

[source, xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.22.2</version>
            <configuration>
                <suiteXmlFiles>
                    <suiteXmlFile>tck-suite.xml</suiteXmlFile>
                </suiteXmlFiles>
            </configuration>
        </plugin>
    </plugins>
</build>
----

== Running as a Scanned Dependency
You can also run the TCK as a scanned dependency.

=== Surefire Configuration in your pom.xml
Once you've added the dependency, you don't need a `tck-suite.xml` you can just scan the dependency for tests.

[source, xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.22.2</version>
            <configuration>
                <dependenciesToScan>
                    <dependency>org.eclipse.microprofile.telemetry:microprofile-telemetry-metrics-tck</dependency>
                </dependenciesToScan>
            </configuration>
        </plugin>
    </plugins>
</build>
----
