//
// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= MicroProfile Telemetry Tracing
:authors: MicroProfile Telemetry Team (Roberto Cortez, Emily Jiang, Bruno Baptista, Jan Westerkamp, Felix Wong, Yasmin Aumeeruddy, Patrik Duditš)
:email: 
:version-label!:
:sectanchors:
:doctype: book
:license: Eclipse Foundation Specification License v1.0
:source-highlighter: coderay
:toc: left
:toclevels: 4
:sectnumlevels: 4
ifdef::backend-pdf[]
:pagenums:
endif::[]
// Attributes defined in the microprofile-telemetry (parent) maven POM:
//:otel-spec-version:
//:otel-spec-main-version:
//:otel-java-version:
//:otel-java-main-version:


// == License
:sectnums!:
include::license-efsl.adoc[]
:sectnums:


== Introduction
In cloud-native technology stacks, distributed and polyglot architectures are the norm.
Distributed architectures introduce a variety of operational challenges including how to solve availability and performance issues quickly.
These challenges have led to the rise of observability.

Telemetry data is needed to power observability products.
Traditionally, telemetry data has been provided by either open-source projects or commercial vendors.
With a lack of standardization, the net result is the lack of data portability and the burden on the user to maintain the instrumentation.

The https://opentelemetry.io[OpenTelemetry] project solves these problems by providing a single, vendor-agnostic solution.

== Architecture
https://opentelemetry.io[OpenTelemetry] is a set of APIs, SDKs, tooling and integrations that are designed for the creation and management of telemetry data such as traces, metrics, and logs.

This specification defines the behaviors that allow MicroProfile applications to easily participate in an environment where distributed tracing is enabled via https://opentelemetry.io[OpenTelemetry] (a merger between https://opentracing.io[OpenTracing] and https://opencensus.io[OpenCensus]).

This document and implementations *MUST* comply with the following OpenTelemetry {otel-spec-main-version} specifications:

* https://github.com/open-telemetry/opentelemetry-specification/blob/v{otel-spec-version}/specification/overview.md[OpenTelemetry Overview]
* https://github.com/open-telemetry/opentelemetry-specification/blob/v{otel-spec-version}/specification/trace/api.md[Tracing API]
* https://github.com/open-telemetry/opentelemetry-specification/blob/v{otel-spec-version}/specification/baggage/api.md[Baggage API]
* https://github.com/open-telemetry/opentelemetry-specification/tree/v{otel-spec-version}/specification/context[Context API]
* https://github.com/open-telemetry/opentelemetry-specification/blob/v{otel-spec-version}/specification/resource/sdk.md[Resource SDK]

[IMPORTANT]
====
The Metrics and Logging integrations of https://opentelemetry.io[OpenTelemetry] are out of scope of this specification.
Implementations are free to provide support for both Metrics and Logging if desired.
====

This specification supports the following three types of instrumentation:

* <<sec:automatic-instrumentation>>
* <<sec:manual-instrumentation>>
* <<sec:agent-instrumentation>>

[[sec:automatic-instrumentation]]
=== Automatic Instrumentation
Jakarta RESTful Web Services (server and client), and MicroProfile REST Clients are automatically enlisted to participate in distributed tracing without code modification as specified in the https://github.com/open-telemetry/opentelemetry-specification/blob/v{otel-spec-version}/specification/trace/api.md[Tracing API].

These should follow the rules specified in the <<sec:semantic-conventions>> section.

[[sec:manual-instrumentation]]
=== Manual Instrumentation
Explicit manual instrumentation can be added into a MicroProfile application in the following ways:

==== @WithSpan
Annotating a method in any Jakarta CDI aware beans with the `io.opentelemetry.instrumentation.annotations.WithSpan` annotation.
This will create a new Span and establish any required relationships with the current Trace context.

Method parameters can be annotated with the `io.opentelemetry.instrumentation.annotations.SpanAttribute` annotation to indicate which method parameters should be part of the Trace.

Example:
[source,java]
----
@ApplicationScoped
class SpanBean {
    @WithSpan
    void span() {

    }

    @WithSpan("name")
    void spanName() {

    }

    @WithSpan(kind = SpanKind.SERVER)
    void spanKind() {

    }

    @WithSpan
    void spanArgs(@SpanAttribute(value = "arg") String arg) {

    }
}
----

==== Obtain a SpanBuilder
By obtaining a `SpanBuilder` from the current `Tracer` and calling `io.opentelemetry.api.trace.Tracer.spanBuilder(String)`.
In this case, it is the developer's responsibility to ensure that the `Span` is properly created, closed, and propagated.

Example:
[source,java]
----
@RequestScoped
@Path("/")
public class SpanResource {
    @Inject
    Tracer tracer;

    @GET
    @Path("/span/new")
    public Response spanNew() {
        Span span = tracer.spanBuilder("span.new")
                .setSpanKind(SpanKind.INTERNAL)
                .setParent(Context.current().with(this.span))
                .setAttribute("my.attribute", "value")
                .startSpan();

        span.end();

        return Response.ok().build();
    }
}
----
 
[NOTE]
====
Start and end a new `Span` will add a child `Span` to the current one enlisted by the automatic instrumentation of Jakarta REST applications.
====

==== Obtain the current Span
By obtaining the current `Span` to add attributes. The Span lifecycle is managed by the implementation.

Example:
[source,java]
----
@RequestScoped
@Path("/")
public class SpanResource {
    @GET
    @Path("/span/current")
    public Response spanCurrent() {
        Span span = Span.current();
        span.setAttribute("my.attribute", "value");
        return Response.ok().build();
    }
}
----

Or with CDI:
[source,java]
----
@RequestScoped
@Path("/")
public class SpanResource {
    @Inject
    Span span;

    @GET
    @Path("/span/current")
    public Response spanCurrent() {
        span.setAttribute("my.attribute", "value");
        return Response.ok().build();
    }
}
----

[[sec:agent-instrumentation]]
=== Agent Instrumentation
Implementations are free to support the OpenTelemetry Agent Instrumentation.
This provides the ability to gather telemetry data without code modifications by attaching a Java Agent JAR to the running JVM.

If an implementation of MicroProfile Telemetry Tracing provides such support, it must conform to the instructions detailed in the https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/v{otel-java-version}[OpenTelemetry Java Instrumentation {otel-java-main-version}] project, including:

* https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/[Agent Configuration]
* https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#suppressing-specific-auto-instrumentation[Suppressing Instrumentation]

Both Agent and MicroProfile Telemetry Tracing Instrumentation (if any), must coexist with each other.

=== Access to the OpenTelemetry Tracing API
An implementation of MicroProfile Telemetry Tracing must provide the following CDI beans for supporting contextual instance injection:

* `io.opentelemetry.api.OpenTelemetry`
* `io.opentelemetry.api.trace.Tracer`
* `io.opentelemetry.api.trace.Span`
* `io.opentelemetry.api.baggage.Baggage`

Calling the OpenTelemetry API directly must work in the same way and yield the same results:

* `io.opentelemetry.api.trace.Span.current()`
* `io.opentelemetry.api.baggage.Baggage.current()`

Implementations MAY support: 

* `io.opentelemetry.api.GlobalOpenTelemetry.get()`

To obtain the `Tracer` with the OpenTelemetry API, the consumer must use the exact same instrumentation name and version used by the implementation.
Failure to do so, may result in a different `Tracer` and incorrect handling of the OpenTelemetry data.


=== Supported OpenTelemetry API Classes

Classes from the following API packages MUST be supported by implementations of this specification, though this specification does not prevent additional API classes from being supported. Implementations are allowed to pull in a more recent patch version of the API classes.

==== Tracing APIs

- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/{otel-java-version}/io/opentelemetry/api/package-summary.html[io.opentelemetry.api] (except `GlobalOpenTelemetry`)
- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/{otel-java-version}/io/opentelemetry/api/trace/package-summary.html[io.opentelemetry.api.trace]
- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/{otel-java-version}/io/opentelemetry/api/common/package-summary.html[io.opentelemetry.api.common]

[NOTE]
====
`io.opentelemetry.api` does depend on https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/{otel-java-version}/io/opentelemetry/api/metrics/package-summary.html[io.opentelemetry.api.metrics] and https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/{otel-java-version}/io/opentelemetry/api/logs/package-summary.html[io.opentelemetry.api.logs], though this specification only supports the parts that relate to Tracing.
====

==== Baggage APIs

- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/{otel-java-version}/io/opentelemetry/api/baggage/package-summary.html[io.opentelemetry.api.baggage]
- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-api/{otel-java-version}/io/opentelemetry/api/baggage/propagation/package-summary.html[io.opentelemetry.api.baggage.propagation]

==== Context API

- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-context/{otel-java-version}/io/opentelemetry/context/package-summary.html[io.opentelemetry.context]
- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-context/{otel-java-version}/io/opentelemetry/context/propagation/package-summary.html[io.opentelemetry.context.propagation]

==== Resource SDK

- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-common/{otel-java-version}/io/opentelemetry/sdk/resources/package-summary.html[io.opentelemetry.sdk.resources]

==== Autoconfigure SPI

This is the programmatic interface that allows users to register extensions when using the SDK Autoconfigure Extension (which we use for configuration). 

- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/{otel-java-version}/io/opentelemetry/sdk/autoconfigure/spi/package-summary.html[io.opentelemetry.sdk.autoconfigure.spi]
- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/{otel-java-version}/io/opentelemetry/sdk/autoconfigure/spi/traces/package-summary.html[io.opentelemetry.sdk.autoconfigure.spi.traces]

The above packages have dependencies on the following packages which must be supported to the extent that they are required by the Autoconfigure SPI classes:

  - https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-trace/{otel-java-version}/io/opentelemetry/sdk/trace/package-summary.html[io.opentelemetry.sdk.trace]
  - https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-trace/{otel-java-version}/io/opentelemetry/sdk/trace/data/package-summary.html[io.opentelemetry.sdk.trace.data]
  - https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-trace/{otel-java-version}/io/opentelemetry/sdk/trace/export/package-summary.html[io.opentelemetry.sdk.trace.export]
  - https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-trace/{otel-java-version}/io/opentelemetry/sdk/trace/samplers/package-summary.html[io.opentelemetry.sdk.trace.samplers]
  - https://www.javadoc.io/static/io.opentelemetry/opentelemetry-sdk-common/{otel-java-version}/io/opentelemetry/sdk/common/package-summary.html[io.opentelemetry.sdk.common]

==== Annotations

- https://www.javadoc.io/doc/io.opentelemetry.instrumentation/opentelemetry-instrumentation-annotations/latest/io/opentelemetry/instrumentation/annotations/package-summary.html[io.opentelemetry.instrumentation.annotations] (`WithSpan` and `SpanAttribute` only)

==== Semantic Conventions

[NOTE]
====
These packages are not stable and may be subject to breaking changes in future releases.
====

- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-semconv/{otel-java-version}-alpha/io/opentelemetry/semconv/trace/attributes/package-summary.html[io.opentelemetry.semconv.trace.attributes]
- https://www.javadoc.io/static/io.opentelemetry/opentelemetry-semconv/{otel-java-version}-alpha/io/opentelemetry/semconv/resource/attributes/package-summary.html[io.opentelemetry.semconv.resource.attributes]

=== Configuration
OpenTelemetry must be configured by MicroProfile Config following the semantics of configuration properties detailed in https://github.com/open-telemetry/opentelemetry-java/tree/v{otel-java-version}/sdk-extensions/autoconfigure[OpenTelemetry SDK Autoconfigure {otel-java-version}].

At minimum the following MicroProfile Config properties MUST be supported:

// Table with property name, default value and description
[options="header"]
|===
|Property Name |Description

// sub-section, colspan=3
2+h| Global Configuration

|`otel.sdk.disabled`
| Set to `false` to enable OpenTelemetry.

Default value: `true`
2+h| Exporters configuration

|`otel.traces.exporter`
| List of exporters to be used for tracing, separated by commas. `none` means no autoconfigured exporter.
  Values other than `none` and `otlp` might link:#sec:service-loader-support[require additional libraries]

Default value: `otlp`

| `otel.propagators`
| The propagators to be used. Values other than `none`, `tracecontext` and `baggage` might link:#sec:service-loader-support[require additional libraries]

Default value: `tracecontext, baggage`

2+h| Resource attributes

| `otel.resource.attributes`
| Specify resource attributes in the following format: `key1=val1, key2=val2, key3=val3`

| `otel.service.name`
| Specify logical service name. Takes precedence over `service.name` defined with `otel.resource.attributes`

Default value: application name (if applicable)

2+h| Batch Span Processor

| `otel.bsp.schedule.delay`
| The interval, in milliseconds, between two consecutive exports.

Default value: `5000`

| `otel.bsp.max.queue.size`
| The maximum queue size.

Default value: `2048`

| `otel.bsp.max.export.batch.size`
| The maximum batch size.

Default value: `512`

| `otel.bsp.export.timeout`
| The maximum allowed time, in milliseconds, to export data.

Default value: `30000`

2+h| Sampler

| `otel.traces.sampler`
a| The sampler to use for tracing. Supported values are:

* `always_on`
* `always_off`
* `traceidratio`
* `parentbased_always_on`
* `parentbased_always_off`
* `parentbased_traceidratio`

Support for other samplers might be added with link:#sec:service-loader-support[additional libraries]

Default value: `parentbased_always_on`

| `otel.traces.sampler.arg`
| An argument to the configured tracer if supported, for example a ratio. Consult OpenTelemetry documentation for details.

2+h| OTLP Exporter

| `otel.exporter.otlp.protocol`
| The transport protocol to use on OTLP trace, metric, and log requests. Options include grpc and http/protobuf.

Default value: `grpc`

| `otel.exporter.otlp.traces.protocol`
| The transport protocol to use on OTLP trace requests. Options include grpc and http/protobuf.

Default value: `grpc`


| `otel.exporter.otlp.endpoint`
| The OTLP traces, metrics, and logs endpoint to connect to. Must be a URL with a scheme of either http or https based on the use of TLS. If protocol is http/protobuf the version and signal will be appended to the path (e.g. v1/traces, v1/metrics, or v1/logs)

Default value: `http://localhost:4317` when protocol is `grpc`, `http://localhost:4318/v1/\{signal}` when protocol is `http/protobuf`

| `otel.exporter.otlp.traces.endpoint`
| The OTLP traces endpoint to connect to. Must be a URL with a scheme of either http or https based on the use of TLS.

Default value: `http://localhost:4317` when protocol is `grpc`, and `http://localhost:4318/v1/traces` when protocol is `http/protobuf`

| `otel.exporter.otlp.certificate`
| The path to the file containing trusted certificates to use when verifying an OTLP trace, metric, or log server's TLS credentials. The file should contain one or more X.509 certificates in PEM format. By default the host platform's trusted root certificates are used.

| `otel.exporter.otlp.traces.certificate`
| The path to the file containing trusted certificates to use when verifying an OTLP trace server's TLS credentials. The file should contain one or more X.509 certificates in PEM format. By default the host platform's trusted root certificates are used.

| `otel.exporter.otlp.client.key`
| The path to the file containing private client key to use when verifying an OTLP trace, metric, or log client's TLS credentials. The file should contain one private key PKCS8 PEM format. By default no client key is used.

| `otel.exporter.otlp.traces.client.key`
| The path to the file containing private client key to use when verifying an OTLP trace client's TLS credentials. The file should contain one private key PKCS8 PEM format. By default no client key file is used.

| `otel.exporter.otlp.client.certificate`
| The path to the file containing trusted certificates to use when verifying an OTLP trace, metric, or log client's TLS credentials. The file should contain one or more X.509 certificates in PEM format. By default no chain file is used.

| `otel.exporter.otlp.traces.client.certificate`
| The path to the file containing trusted certificates to use when verifying an OTLP trace server's TLS credentials. The file should contain one or more X.509 certificates in PEM format. By default no chain file is used.

| `otel.exporter.otlp.headers`
| Key-value pairs separated by commas to pass as request headers on OTLP trace, metric, and log requests.

| `otel.exporter.otlp.traces.headers`
| Key-value pairs separated by commas to pass as request headers on OTLP trace requests.

| `otel.exporter.otlp.compression`
| The compression type to use on OTLP trace, metric, and log requests. Options include gzip. By default no compression will be used.

| `otel.exporter.otlp.traces.compression`
| The compression type to use on OTLP trace requests. Options include gzip. By default no compression will be used.

| `otel.exporter.otlp.timeout`
| The maximum waiting time, in milliseconds, allowed to send each OTLP trace, metric, and log batch.

Default value: `10000`

| `otel.exporter.otlp.traces.timeout`
| The maximum waiting time, in milliseconds, allowed to send each OTLP trace batch.

Default value: `10000`
|===

If Environment Config Source is enabled for MicroProfile Config, then the environment variables as described by the OpenTelemetry SDK Autoconfigure are also supported.

[[sec:service-loader-support]]
==== Service Loader Support

Implementation will load additional configuration related components by means of service loader.
This allows the application to define its own metadata and trace handling behavior.
The following components are supported

[options=header]
|===
| Component interface | Purpose

| https://javadoc.io/doc/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/{otel-java-version}/io/opentelemetry/sdk/autoconfigure/spi/ConfigurablePropagatorProvider.html[`ConfigurablePropagatorProvider`]
| Provides implementation for a name referred in `otel.propagators`

| https://javadoc.io/doc/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/{otel-java-version}/io/opentelemetry/sdk/autoconfigure/spi/traces/ConfigurableSpanExporterProvider.html[`ConfigurableSpanExporterProvider`]
| Provides implementation for a name referred in `otel.traces.exporter`

| https://javadoc.io/doc/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/{otel-java-version}/io/opentelemetry/sdk/autoconfigure/spi/traces/ConfigurableSamplerProvider.html[`ConfigurableSamplerProvider`]
| Provides implementation for a name referred in `otel.traces.sampler`

| https://javadoc.io/doc/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/{otel-java-version}/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizerProvider.html[`AutoConfigurationCustomizerProvider`]
| Customizes configuration properties before they are applied to the SDK

| https://javadoc.io/doc/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/{otel-java-version}/io/opentelemetry/sdk/autoconfigure/spi/ResourceProvider.html[`ResourceProvider`]
| Defines resource attributes describing the application
|===

Behavior when multiple implementations are found for a given component name is undefined.
Behavior when customizer changes other properties than those listed in the spec is also undefined.

[[sec:semantic-conventions]]
=== Semantic Conventions
The https://github.com/open-telemetry/opentelemetry-specification/tree/v{otel-spec-version}/specification/trace/semantic_conventions[Trace Semantic Conventions] for Spans and Attributes must be followed by any compatible implementation.

All attributes marked as `required` must be present in the context of the Span where they are defined.
Any other attribute is optional.
Implementations can also add their own attributes.

==== MicroProfile Attributes
Other MicroProfile specifications can add their own attributes under their own attribute name following the convention `mp.[specification short name].[attribute name]`.

Implementation libraries can set the library name using the following property:

`mp.telemetry.tracing.name`

== Tracing Enablement
By default, MicroProfile Telemetry Tracing is deactivated.

In order to enable any of the tracing aspects, the configuration `otel.sdk.disabled=false` must be specified in any of the configuration sources available via MicroProfile Config.

// TODO The hard coded otel-spec-version need to be replaced in future spec releases!
[IMPORTANT]
====
This is a deviation from the https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/overview.md[OpenTelemetry Specification version 1.14.0] that specifies this configuration property officially, where https://opentelemetry.io[OpenTelemetry] is activated by default!

But in fact, it will be activated only by adding it's dependency to the application or platform project.
To be able to add MicroProfile Telemetry Tracing to MicroProfile implementations by default without side effects, this deviating behaviour has been defined here (see also <<sec:microprofile-telemetry-and-microprofile-opentracing>>).

The original definition for this configuration property and the corresponding `OTEL_SDK_DISABLED` environment variable is specified in the https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/sdk-environment-variables.md#opentelemetry-environment-variable-specification[OpenTelemetry Environment Variable Specification version 1.14.0] and it's https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/sdk-environment-variables.md#general-sdk-configuration[General SDK Configuration].
====

This property is read once when the application is starting.
Any changes afterwards will not take effect unless the application is restarted.

== MicroProfile OpenTracing
MicroProfile Telemetry Tracing supersedes MicroProfile OpenTracing.
Even if the end goal is the same, there are some considerable differences:

* Different API (between OpenTracing and OpenTelemetry)
* No `@Traced` annotation
* No specific MicroProfile configuration
* No customization of Span name through MicroProfile API
* Differences in attribute names and mandatory ones

For these reasons, the MicroProfile Telemetry Tracing specification does not provide any migration path between both projects.
While it is certainly possible to achieve a migration path at the code level and at the specification level (at the expense of not following the main OpenTelemetry specification), it is unlikely to be able to achieve the same compatibility at the data layer.
Regardless, implementations are still free to provide migration paths between MicroProfile OpenTracing and MicroProfile Telemetry Tracing. 

If a migration path is provided, the bridge layer provided by OpenTelemetry should be used.
This bridge layer implements OpenTracing APIs using OpenTelemetry APIs (more details can be found from https://github.com/open-telemetry/opentelemetry-specification/blob/v{otel-spec-version}/specification/compatibility/opentracing.md[OpenTracing Compatbility]. 
The bridge layer takes OpenTelemetry Tracer and exposes as OpenTracing Tracer.
See the example below.

[source,java]
----
//From the global OpenTelemetry configuration
Tracer tracer1 = OpenTracingShim.createTracerShim();
//From a provided OpenTelemetry instance oTel
Tracer tracer2 = OpenTracingShim.createTracerShim(oTel);
----

Afterwards, you can then register the tracer as the OpenTracing Global Tracer:

[source,java]
----
GlobalTracer.registerIfAbsent(tracer);
----

[[sec:microprofile-telemetry-and-microprofile-opentracing]]
== MicroProfile Telemetry and MicroProfile OpenTracing
If MicroProfile Telemetry and MicroProfile OpenTracing are both present in one application, it is advised only to enable one of them.
Otherwise, no portable behaviour may occur.
